name: Build main
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: validate files
      run:  curl -X POST  --data "data=$(cat *.yml)" https://www.lint-trilogy.com/lint/yaml/json
